name Deploy to GitHub Pages

on
  push
    branches
      - main

jobs
  deploy
    runs-on ubuntu-latest

    steps
      - name Checkout code
        uses actionscheckout@v3

      - name Deploy to GitHub Pages
        uses peaceirisactions-gh-pages@v3
        with
          github_token ${{ secrets.GITHUB_TOKEN }}
          publish_dir .public